name: Docker Image CI

on:
    push:
      branches: [ "main","data_generation_migration" ]
    pull_request:
      branches: [ "main","data_generation_migration" ]


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        r-version: ['3.6.3', '4.1.1']
  


    steps:
      - uses: actions/checkout@v4

      - name: Set up R ${{ matrix.r-version }}
        # uses: r-lib/actions/setup-r@f57f1301a053485946083d7a45022b278929a78a
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r-version }}

      - name: Install dependencies
        shell: Rscript 
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE)
      - name: Check
        shell: Rscript 
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")

      - name: Check Data Generation
        shell: Rscript 
        run: generate_fake_data.R

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag hombergn/hadaca3_light
      
      - name: Create submission program
        shell: Rscript 
        run: starting_kit/submission_script.R
      - name: Prepare files
        shell: bash
        run: |
          chmod +x prepare2score_locally.sh
          prepare2score_locally.sh
      - name: Running ingestion Program
        run: docker run --rm  -v $PWD/ingestion_program:/app/program  -v $PWD/test_output/res:/app/output  -v $PWD/starting_kit/submissions:/app/ingested_program  -w /app/program  -v $PWD/input_data:/app/input_data hombergn/hadaca3_light Rscript /app/program/ingestion.R /app/program /app/input_data /app/output /app/ingested_program 
        
        
      - name: Running Scoring Program
        # sudo docker run --rm  -v $PWD/ingestion_program:/app/program  -v $PWD/test_output/res:/app/output  -v $PWD/starting_kit/submissions:/app/ingested_program  -w /app/program  -v $PWD/input_data:/app/input_data hombergn/hadaca3_light Rscript /app/program/ingestion.R /app/program /app/input_data /app/output /app/ingested_program >> logs 
        run: docker run --rm  -v $PWD/scoring_program:/app/program  -v $PWD/test_output:/app/output  -w /app/program  -v $PWD/test_output:/app/input  hombergn/hadaca3_light  Rscript /app/program/scoring.R /app/input /app/output /app/program



    
